"use strict";
/*

    Pawfect Nibbles & Bites
    Internship Project
    
    Pawfect Nibbles & Bites
    Treat Data JS

    Author:  Meghan Wilkerson
    Date:    2026-03-28

    Filename: PNB_TreatData.js

*/

/* ==================
   Treat Data Objects
   ================== */

const treatData = {
  appleOatitude: {
    name: "Apple Oat-itude",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "Graphics/Treats/Nibbles_AppleOatitude.webp",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["Graphics/Treats/Nibbles_AppleOatitude.webp"],
      bites: ["Graphics/Treats/Bites_AppleOatitude.webp"],
      chews: ["Graphics/Treats/Chews_AppleOatitude.webp"],
      chomps: ["Graphics/Treats/Chomps_AppleOatitude.webp"]
    } 
  },
  bananaNutty: {
    name: "BananaNutty",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "Graphics/Treats/Nibbles_BananaNutty.webp",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["Graphics/Treats/Nibbles_BananaNutty.webp"],
      bites: ["Graphics/Treats/Bites_BananaNutty.webp"],
      chews: ["Graphics/Treats/Chews_BananaNutty.webp"],
      chomps: ["Graphics/Treats/TreatPhotosComingSoon.png"]
    } 
  },
  blueAppleBash: {
    name: "Blue-Apple Bash",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "Graphics/Treats/Nibbles_BlueAppleBash.webp",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["Graphics/Treats/Nibbles_BlueAppleBash.webp"],
      bites: ["Graphics/Treats/TreatPhotosComingSoon.png"],
      chews: ["Graphics/Treats/TreatPhotosComingSoon.png"],
      chomps: ["Graphics/Treats/TreatPhotosComingSoon.png"]
    } 
  },
  goldenStrides: {
    name: "Golden Strides",
    prices: { nibbles: 4.99 },
    img: "Graphics/Treats/Nibbles_GoldenStrides.webp",
    availableSizes: ["nibbles"], 
    images: {
      nibbles: ["Graphics/Treats/Nibbles_GoldenStrides.webp"]
    },
  },
  pbPunkin: {
    name: "PB Punkin",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "Graphics/Treats/Nibbles_PBPunkin.webp",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["Graphics/Treats/Nibbles_PBPunkin.webp"],
      bites: ["Graphics/Treats/Bites_PBPunkin.webp"],
      chews: ["Graphics/Treats/Chews_PBPunkin.webp"],
      chomps: ["Graphics/Treats/TreatPhotosComingSoon.png"]
    }
  }
};