"use strict";
/*

    Pawfect Nibbles & Bites
    Internship Project
    
    Pawfect Nibbles & Bites
    Treat Data JS

    Author:  Meghan Wilkerson
    Date:    2026-03-28

    Filename: PNB_TreatData.js

*/

/* ----------
   TREAT DATA
   ---------- */

const treatData = {
  appleOatitude: {
    name: "Apple Oat-itude",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "../Graphics/Treats/Nibbles_AppleOatitude.jpg",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["../Graphics/Treats/Nibbles_AppleOatitude.jpg"],
      bites: ["../Graphics/Treats/Bites_AppleOatitude.jpg"],
      chews: ["../Graphics/Treats/Chews_AppleOatitude.jpg"],
      chomps: ["../Graphics/Treats/Chomps_AppleOatitude.jpg"]
    } 
  },
  bananaNutty: {
    name: "BananaNutty",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "../Graphics/Treats/Nibbles_BananaNutty.jpg",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["../Graphics/Treats/Nibbles_BananaNutty.jpg"],
      bites: ["../Graphics/Treats/Bites_BananaNutty.jpg"],
      chews: ["../Graphics/Treats/Chews_BananaNutty.jpg"],
      chomps: ["../Graphics/Treats/TreatPhotosComingSoon.png"]
    } 
  },
  blueAppleBash: {
    name: "Blue-Apple Bash",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "../Graphics/Treats/Nibbles_BlueAppleBash.jpg",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["../Graphics/Treats/Nibbles_BlueAppleBash.jpg"],
      bites: ["../Graphics/Treats/TreatPhotosComingSoon.png"],
      chews: ["../Graphics/Treats/TreatPhotosComingSoon.png"],
      chomps: ["../Graphics/Treats/TreatPhotosComingSoon.png"]
    } 
  },
  goldenStrides: {
    name: "Golden Strides",
    prices: { nibbles: 4.99 },
    img: "../Graphics/Treats/Nibbles_GoldenStrides.jpg",
    availableSizes: ["nibbles"], 
    images: {
      nibbles: ["../Graphics/Treats/Nibbles_GoldenStrides.jpg"]
    },
  },
  pbPunkin: {
    name: "PB Punkin",
    prices: { nibbles: 4.99, bites: 6.99, chews: 9.99, chomps: 11.99 },
    img: "../Graphics/Treats/Nibbles_PBPunkin.jpg",
    availableSizes: ["nibbles", "bites", "chews", "chomps"],
    images: {
      nibbles: ["../Graphics/Treats/Nibbles_PBPunkin.jpg"],
      bites: ["../Graphics/Treats/Bites_PBPunkin.jpg"],
      chews: ["../Graphics/Treats/Chews_PBPunkin.jpg"],
      chomps: ["../Graphics/Treats/TreatPhotosComingSoon.png"]
    }
  }
};